import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextFont } from 'next/dist/compiled/@next/font';
import React, { ReactNode, Suspense } from 'react';
import { ToasterContext } from './context/ToastContext';
import './styles/globals.css';
import { TopHeader } from './components/header';
import { Footer } from './components/footer';

const inter: NextFont = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: '午後のガレージ',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <Suspense>
                <body className={inter.className}>
                    <ToasterContext />
                    <div>
                        <TopHeader />
                        {children}
                        <Footer />
                    </div>
                </body>
            </Suspense>
        </html>
    );
}
